# Generated by Django 5.1.7 on 2025-09-16 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='last_name',
        ),
    ]
