# Generated by Django 5.2.6 on 2025-09-14 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_alter_appointments_doctor_alter_appointments_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='insurance',
        ),
        migrations.AddField(
            model_name='insurance',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_api.patient'),
        ),
    ]
