# Generated by Django 5.2.6 on 2025-09-14 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_remove_patient_insurance_insurance_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='name',
            new_name='plan_name',
        ),
        migrations.AlterField(
            model_name='insurance',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance', to='core_api.patient'),
        ),
    ]
