# Generated by Django 5.1.7 on 2025-09-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_patientdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdocument',
            name='paperless_id',
            field=models.CharField(max_length=100),
        ),
    ]
